name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          GCP_SCREENER_BAKE_SA: ${{ secrets.GCP_SCREENER_BAKE_SA }}
          GCP_SCREENER_DEPLOY_SA: ${{ secrets.GCP_SCREENER_DEPLOY_SA }}
          GCP_WIF_PROVIDER: ${{ secrets.GCP_WIF_PROVIDER }}
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add GCP_SCREENER_BAKE_SA="$GCP_SCREENER_BAKE_SA" GCP_SCREENER_DEPLOY_SA="$GCP_SCREENER_DEPLOY_SA" GCP_WIF_PROVIDER="$GCP_WIF_PROVIDER" RELEASE_TOKEN="$RELEASE_TOKEN" --repo ditto-assistant/ditto-screener
